import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | All In One Calculator',
  description: 'Read the Terms of Service for All In One Calculator.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-8">
      <div className="space-y-4 border-b border-gray-100 pb-8">
        <h1 className="text-4xl md:text-5xl font-display font-bold text-gray-900">Terms of Service</h1>
        <p className="text-gray-500">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
      </div>

      <div className="text-gray-600 space-y-6 leading-relaxed">
        <p>
          Welcome to All In One Calculator. By accessing or using our website, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Use of the Site and Tools</h3>
        <p>
          All In One Calculator provides free online calculation tools for informational and educational purposes only. While we strive to ensure our formulas are accurate, the results provided by our calculators are estimates and should not be considered definitive.
        </p>
        <p>
          <strong>No Professional Advice:</strong> The content and results generated by our finance, health, and legal calculators do not constitute professional financial, medical, or legal advice. You should always consult with a qualified professional before making significant decisions based on these calculations.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">2. Disclaimer of Warranties</h3>
        <p>
          The service is provided on an "AS IS" and "AS AVAILABLE" basis. All In One Calculator makes no representations or warranties of any kind, express or implied, as to the operation of their services, or the information, content, or materials included therein.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">3. Limitation of Liability</h3>
        <p>
          In no event shall All In One Calculator, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">4. Intellectual Property</h3>
        <p>
          The Service and its original content, features, and functionality are and will remain the exclusive property of All In One Calculator and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">5. Changes to Terms</h3>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
        </p>

        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-4">6. Contact Us</h3>
        <p>
          If you have any questions about these Terms, please contact us at <strong>legal@allinonecalculator.fun</strong>.
        </p>
      </div>
    </div>
  );
}
